package com.example.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA entity for the 'account_network_scores' table - one row per account
 * PER RUN (append-only, never overwritten - see NetworkRun). Written by the
 * Python/NetworkX batch job; read-only from the Spring side.
 *
 * accountId is a plain column (not a @ManyToOne to Account) deliberately:
 * the Python job only ever needs to know the integer account_id to write a
 * row, so it doesn't have to understand the full JPA object graph - this
 * keeps the cross-language contract to "insert into these columns".
 */
@Entity
@Table(
    name = "account_network_scores",
    indexes = {
        @Index(name = "idx_net_score_account_computed", columnList = "account_id, computed_at"),
        @Index(name = "idx_net_score_run", columnList = "run_id")
    }
)
public class AccountNetworkScore {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "run_id", nullable = false)
    private Integer runId;

    @Column(name = "account_id", nullable = false)
    private Integer accountId;

    // Final weighted, 0-100 score (see riskengine convention on Case.riskScore) -
    // combines all individual signals below via the configured weighting strategy.
    @Column(name = "network_risk_score", nullable = false, precision = 5, scale = 2)
    private BigDecimal networkRiskScore;

    // Individual signals, stored both as their own columns (for cheap sorting/
    // filtering) AND inside evidenceJson (for full explainability without
    // needing a schema change every time a new signal is added).
    @Column(name = "page_rank_percentile", precision = 5, scale = 2)
    private BigDecimal pageRankPercentile;

    @Column(name = "shared_payee_count")
    private Integer sharedPayeeCount;

    @Column(name = "community_id")
    private Integer communityId;

    @Column(name = "community_size")
    private Integer communitySize;

    @Column(name = "growth_score", precision = 5, scale = 2)
    private BigDecimal growthScore;

    @Column(name = "fraud_exposure_score", precision = 5, scale = 2)
    private BigDecimal fraudExposureScore;

    // Raw per-signal values as JSON, e.g.
    // {"page_rank": 0.81, "shared_payees": 17, "community_size": 11,
    //  "growth_score": 0.63, "fraud_exposure": 0.92}
    // Lets Spring build an explainability breakdown without re-running Python.
    @Column(name = "evidence_json", columnDefinition = "JSON")
    private String evidenceJson;

    // Human-readable explanation generated by the Python job at compute time,
    // e.g. "High PageRank score due to links with two confirmed fraud
    // accounts. Shares three frequently used payees with eight other
    // high-risk accounts." Spring/React just display this verbatim.
    @Column(name = "network_reason", columnDefinition = "TEXT")
    private String networkReason;

    @Column(name = "computed_at", nullable = false)
    private LocalDateTime computedAt;

    public AccountNetworkScore() {
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Integer getRunId() { return runId; }
    public void setRunId(Integer runId) { this.runId = runId; }
    public Integer getAccountId() { return accountId; }
    public void setAccountId(Integer accountId) { this.accountId = accountId; }
    public BigDecimal getNetworkRiskScore() { return networkRiskScore; }
    public void setNetworkRiskScore(BigDecimal networkRiskScore) { this.networkRiskScore = networkRiskScore; }
    public BigDecimal getPageRankPercentile() { return pageRankPercentile; }
    public void setPageRankPercentile(BigDecimal pageRankPercentile) { this.pageRankPercentile = pageRankPercentile; }
    public Integer getSharedPayeeCount() { return sharedPayeeCount; }
    public void setSharedPayeeCount(Integer sharedPayeeCount) { this.sharedPayeeCount = sharedPayeeCount; }
    public Integer getCommunityId() { return communityId; }
    public void setCommunityId(Integer communityId) { this.communityId = communityId; }
    public Integer getCommunitySize() { return communitySize; }
    public void setCommunitySize(Integer communitySize) { this.communitySize = communitySize; }
    public BigDecimal getGrowthScore() { return growthScore; }
    public void setGrowthScore(BigDecimal growthScore) { this.growthScore = growthScore; }
    public BigDecimal getFraudExposureScore() { return fraudExposureScore; }
    public void setFraudExposureScore(BigDecimal fraudExposureScore) { this.fraudExposureScore = fraudExposureScore; }
    public String getEvidenceJson() { return evidenceJson; }
    public void setEvidenceJson(String evidenceJson) { this.evidenceJson = evidenceJson; }
    public String getNetworkReason() { return networkReason; }
    public void setNetworkReason(String networkReason) { this.networkReason = networkReason; }
    public LocalDateTime getComputedAt() { return computedAt; }
    public void setComputedAt(LocalDateTime computedAt) { this.computedAt = computedAt; }
}
