/**
 * TransactionSource Enum
 * 
 * PURPOSE: Marks where a transaction came from in the system.
 *   - API: Transaction created by an external caller via REST endpoint
 *   - SIMULATOR: Transaction auto-generated by the background simulator (test data)
 * 
 * USAGE: Lets us filter and separate real API transactions from fake simulator data
 *        when running reports or debugging.
 */
package com.example.enums;

public enum TransactionSource {
    API,
    SIMULATOR
}
